FROM node:18

WORKDIR /app/medusa

COPY ./medusa-storefront/package.json .


COPY medusa-storefront/yarn.* .

RUN apt-get update

RUN npm install -g npm

# RUN npm install -g @medusajs/medusa-cli@latest

RUN npm install

COPY ./medusa-storefront .


#RUN npm run build

ENTRYPOINT ["npm", "run", "dev"]

