FROM node:18

WORKDIR /app/medusa

COPY ./medusa-admin/package.json .


COPY medusa-admin/yarn.* .

RUN apt-get update

RUN npm install -g npm

# RUN npm install -g @medusajs/medusa-cli@latest

RUN npm install

COPY ./medusa-admin .
RUN sed 's/"dev": "vite --port 7000"/"dev": "vite --port 7000 --host"/; s/"preview": "vite preview --port 7000"/"preview": "vite preview --port 7000 --host"/' ./package.json > package.json.copy
RUN cp package.json.copy package.json

ENTRYPOINT ["npm", "start"]

