name: Deploy to Heroku
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Build the app
        run: npm run build
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'YOUR_HEROKU_APP_NAME'
      - name: Deploy to Heroku
        run: npm run deploy